### ISSUE TITLE
Time display incorrect

### ISSUE THREAD

**Issue by armm29393** [anthonyeden/ProPresenter-Lyrics-HTML#1]
Time display as timestamp.
![image](https://user-images.githubusercontent.com/22807984/79524937-f0623980-808b-11ea-9a0c-0fbbc175137d.png)

**Comment by anthonyeden** [comment]
What version of ProPresenter do you run?
6 or 7?
Windows or Mac?

**Comment by armm29393** [comment]
ProPresenter 7 on Windows 10 x64

**Comment by armm29393** [comment]
Thank you @williamhatcher
another version by me https://github.com/armm29393/ProPresenter-Lyrics-HTML/commit/16d99c
